---
language: python
matrix:
  include:
    - os: linux
      python: 3.6
    - os: osx
      language: generic
      env: PYTHON=3.6
branches:
  only:
    - master
addons:
  chrome: stable
cache:
  - pip
before_install:
  - scripts/travis-prep-osx.sh
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - pipenv run check-format
  - pipenv run test
