---
language: python
os:
  - linux
  - osx
branches:
  only:
    - master
python:
  - 3.6
addons:
  chrome: stable
cache:
  - pip
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - pipenv run test
